# Theme Settings
remote_theme: "ChristopherA/BaseTheme@main"
plugins:
  - jekyll-remote-theme # Required
  - jekyll-seo-tag      # Required by BaseTheme
  - jekyll-feed         # Optional enhancement
  - jekyll-sitemap      # Optional enhancement
  - jekyll-paginate     # Optional pagination

# Pagination Settings
paginate: 5
paginate_path: "/blog/page:num/"

# Site Settings
title: "Demo Site"
description: "A site built using BaseTheme."
url: "https://ChristopherA.github.io"
baseurl: "/BaseTheme-DemoSite"

# Optional Settings
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
date_format: "%B %d, %Y"

# Jekyll Settings
markdown: kramdown
collections:
  pages:
    output: true
