# Theme Settings
remote_theme: "ChristopherA/BaseTheme@main"
plugins:
  - jekyll-remote-theme  # Required for remote theme

# Site Settings
title: "Demo Site"
description: "A site built using BaseTheme."
url: "https://ChristopherA.github.io"
baseurl: "/BaseTheme-DemoSite"

# Optional Settings
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
date_format: "%B %d, %Y"

# Jekyll Settings
markdown: kramdown
collections:
  pages:
    output: true
