# DemoSite Configuration
# Demonstrates BaseTheme usage with both static pages and blog posts

# Theme Settings
remote_theme: "ChristopherA/BaseTheme@main"

# REQUIRED: Site Settings 
# >>> CHANGE THESE TO YOUR OWN VALUES <<<
title: "Demo Site"                        # Change to your website's title
description: "A site built using BaseTheme." # Change to your site's description
url: "https://ChristopherA.github.io"     # Change to your own github.io URL
baseurl: "/BaseTheme-DemoSite"           # Change to your repository name, or "" if hosting at root

# OPTIONAL: SEO Enhancements (jekyll-seo-tag)
# >>> CHANGE THESE TO YOUR OWN SOCIAL MEDIA, OR REMOVE IF NOT NEEDED <<<
twitter:
  username: ChristopherA                  # Change to your Twitter username, or remove section if unused
  card: summary                          

social:
  name: Christopher Allen                # Change to your name
  links:                                # Change to your own social media URLs, or remove unused ones
    - https://bsky.app/profile/christophera.bsky.social
    - https://github.com/ChristopherA
    - https://twitter.com/ChristopherA
    - https://www.linkedin.com/in/ChristopherA

# Required and Optional Plugins
plugins:
  # Core functionality (inherited from BaseTheme)
  - jekyll-remote-theme                  # Required - do not remove
  - jekyll-seo-tag                      # Required - do not remove
  - jekyll-sitemap                      # Required - do not remove
  
  # OPTIONAL: Quality of life improvements
  # >>> REMOVE THESE IF NOT NEEDED <<<
  - jekyll-default-layout              # Optional - removes need for layout in front matter
  - jekyll-titles-from-headings         # Optional - removes need for title in front matter

  # OPTIONAL: Blog-specific features
  # >>> REMOVE THIS SECTION IF NOT USING BLOG POSTS <<<
  - jekyll-feed                        # Optional - generates RSS feed for blog posts

# OPTIONAL: Plugin Configurations
# >>> REMOVE THIS SECTION IF NOT USING jekyll-titles-from-headings <<<
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# REQUIRED: Navigation
# >>> CHANGE THESE TO YOUR OWN PAGES <<<
navigation:
  - title: Home
    url: /
  - title: About                        # Remove if not using
    url: /about/
  - title: Blog                         # Remove if not using blog
    url: /blog/

# Format Settings
date_format: "%B %d, %Y"                # How dates appear (e.g., November 22, 2024)

# Jekyll Settings
markdown: kramdown                      
collections:                           
  pages:                              
    output: true                     

# OPTIONAL: Feed Settings
# >>> REMOVE THIS SECTION IF NOT USING BLOG POSTS <<<
feed:
  path: feed.xml                       
  posts_limit: 20
